apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: public-sporingslogg-loggmeldingmottatt-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  pool: nav-dev
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact, compact,delete
    minimumInSyncReplicas: 1
    partitions: 2
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730  # -1 means unlimited
  acl:
    - team: pensjonsamhandling
      application: sporingslogg-q2
      access: read   # read, write, readwrite
    - team: pensjonsamhandling
      application: dsop-ufo
      access: write
    - team: pensjonsamhandling
      application: pensjon-sporingslogg-integrasjon
      access: write
    - team: teamarenanais
      application: arena-dsop-api-q2
      access: write
#    - team: pensjon
#      application: pensjon-q2
#      access: write   #write
#    - team: andre
#      application: team-andre
#      access: write