version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
