version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - patch
          - minor
    allow:
      - dependency-type: "direct"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10