FROM navikt/java:8
LABEL maintainer="aage.kramarics@nav.no"

# Passord ligger i angitt vault-fil (key=value format), med angitt key
ENV PASSWORD_FILE="/var/run/secrets/nais.io/vault/secrets.properties"

ENV LDAP_URL="ldaps://ldapgw.test.local"
ENV LDAP_USERNAME="srvsporingslogg"
# vault: ENV LDAP_PASSWORD
ENV LDAP_BASEDN="DC=test,DC=local"
ENV LDAP_USER_BASEDN="ou=NAV,ou=BusinessUnits,dc=test,dc=local"
ENV LDAP_SERVICEUSER_BASEDN="ou=ServiceAccounts,dc=test,dc=local"

ENV SPORINGSLOGGDB_URL="jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=d26dbfl021.test.local)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=SPORINGSLOGGT4)(INSTANCE_NAME=cctf02)(UR=A)(SERVER=DEDICATED)))"
ENV SPORINGSLOGGDB_USERNAME="SPORINGSLOGG_T4"
# vault: ENV SPORINGSLOGGDB_PASSWORD

ENV NO_NAV_SPORINGSLOGG_KAFKA_USERNAME="srvsporingslogg"
# vault: ENV NO_NAV_SPORINGSLOGG_KAFKA_PASSWORD  

ENV NO_NAV_SPORINGSLOGG_KAFKA_TOPIC="aapen-sporingslogg-loggmeldingMottatt"
ENV NO_NAV_SPORINGSLOGG_KAFKA_SERVERS="d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443"
      
# OIDC-ressursene er annerledes for idporten/openam
ENV NO_NAV_SPORINGSLOGG_OIDC_ISSUER="https://security-token-service-t10.nais.preprod.local"
ENV NO_NAV_SPORINGSLOGG_OIDC_JWKS="https://security-token-service-t10.nais.preprod.local/rest/v1/sts/jwks"
# Skal være satt til 4 (Bank-ID) når man går mot ID-porten, 0 ellers
ENV SPORINGSLOGG_CHECK_AUTHLEVEL="0"

COPY sporingslogg-web/target/sporingslogg-web.jar /app/app.jar

# Expose default http jetty port
EXPOSE 8088
