FROM navikt/java:8
LABEL maintainer="aage.kramarics@nav.no"

# Passord ligger i angitt vault-fil (key=value format), med angitt key
ENV PASSWORD_FILE="/var/run/secrets/nais.io/vault/secrets.properties"

ENV LDAP_URL="ldaps://ldapgw.adeo.no"
ENV LDAP_USERNAME="srvsporingslogg"
# vault: ENV LDAP_PASSWORD
ENV LDAP_BASEDN="dc=adeo,dc=no"
ENV LDAP_USER_BASEDN="ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
ENV LDAP_SERVICEUSER_BASEDN="ou=ServiceAccounts,dc=adeo,dc=no"

ENV SPORINGSLOGGDB_URL="jdbc:oracle:thin:@a01dbfl043.adeo.no:1521/SPORINGSLOGG_P_HA"
ENV SPORINGSLOGGDB_USERNAME="SPORINGSLOGG"
# vault: ENV SPORINGSLOGGDB_PASSWORD

ENV NO_NAV_SPORINGSLOGG_KAFKA_USERNAME="srvsporingslogg"
# vault: ENV NO_NAV_SPORINGSLOGG_KAFKA_PASSWORD  

ENV NO_NAV_SPORINGSLOGG_KAFKA_TOPIC="aapen-sporingslogg-loggmeldingMottatt"
ENV NO_NAV_SPORINGSLOGG_KAFKA_SERVERS="a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"
      
# OIDC-ressursene er annerledes for idporten/openam
ENV NO_NAV_SPORINGSLOGG_OIDC_ISSUER="https://security-token-service.nais.adeo.no"
ENV NO_NAV_SPORINGSLOGG_OIDC_JWKS="https://security-token-service.nais.adeo.no/rest/v1/sts/jwks"
# Skal være satt til 4 (Bank-ID) når man går mot ID-porten, 0 ellers
ENV SPORINGSLOGG_CHECK_AUTHLEVEL="0"

COPY sporingslogg-web/target/sporingslogg-web.jar /app/app.jar

# Expose default http jetty port
EXPOSE 8088
