# Miljøspesifikke verdier: metadata.namespace, spec.ingresses, og spec.env-verdiene
# image-navnet injiseres med riktig versjon
#
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg
  namespace: default
  labels:
    team: integrasjon
spec:
  image: _IMAGE_FULLNAME_
  port: 8088
  ingresses:
    - "https://sporingslogg.nais.adeo.no"
  secureLogs:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  liveness:
    path: /sporingslogg/api/ping
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    path: /sporingslogg/api/ping
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 60
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault: 
    enabled: true
  env:
    - name: LDAP_URL
      value: "ldaps://ldapgw.adeo.no"
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"
    - name: SPORINGSLOGGDB_URL
      value: "jdbc:oracle:thin:@a01dbfl043.adeo.no:1521/SPORINGSLOGG_P_HA"
    - name: SPORINGSLOGGDB_USERNAME
      value: "SPORINGSLOGG"
    - name: NO_NAV_SPORINGSLOGG_KAFKA_SERVERS
      value: "a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"
# OIDC-ressursene er annerledes for idporten/openam
    - name: NO_NAV_SPORINGSLOGG_OIDC_ISSUER
      value: "https://login.microsoftonline.com/8b7dfc8b-b52e-4741-bde4-d83ea366f94f/v2.0/"
    - name: NO_NAV_SPORINGSLOGG_OIDC_JWKS
      value: "https://login.microsoftonline.com/navnob2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten"
# Skal være satt til 4 (Bank-ID) når man går mot ID-porten, 0 ellers
    - name: SPORINGSLOGG_CHECK_AUTHLEVEL
      value: "4"
# Må sette opp web proxy hvis JWKS-URL er ekstern
    - name: NO_NAV_SPORINGSLOGG_OIDC_PROVIDER_PROXYHOST
      value: "webproxy-nais.nav.no"
    - name: NO_NAV_SPORINGSLOGG_OIDC_PROVIDER_PROXYPORT
      value: "8088"
      