no.nav.security.jwt:
  issuer:
    tokendings:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
    entraid:
     discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
     accepted_audience: ${AZURE_APP_CLIENT_ID}
kafka:
  security.protocol: SSL
  sporingslogg:
    aiventopic: ${SPORINGSLOGG_AIVEN_KAFKA_TOPIC}
    aivengroupid: ${SPORINGSLOGG_AIVEN_KAFKA_GROUP}

management:
  endpoint:
    health:
      show-details: always
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
spring:
  datasource:
    url: ${DBURL}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    hikari:
      maximum-pool-size: 3
      idle-timeout: 300000
      max-lifetime: 1800000
  flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 1
  web:
    error:
      include-message: always
