apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  envFrom:
    - secret: sporingslogg-q2
  azure:
    application:
      allowAllUsers: false
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dsop-api # Fjernes når tms-personopplysninger-api har tatt over
          namespace: personbruker
          cluster: dev-gcp
        - application: tms-personopplysninger-api  # Tar over for dsop-api
          namespace: min-side
          cluster: dev-gcp
        - application: pensjon-pen-q0
          namespace: pensjon-q0
          cluster: dev-fss
        - application: pensjon-pen-q1
          namespace: pensjon-q1
          cluster: dev-fss
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-pen-q5
          namespace: pensjon-q5
          cluster: dev-fss
        - application: pensjonssimulator
          namespace: pensjonskalkulator
          cluster: dev-gcp
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sporingslogg-q2.dev.intern.nav.no"
    - "https://sporingslogg-q2.dev-fss-pub.nais.io"
  secureLogs:
    enabled: false
  prometheus:
    enabled: true
    path: actuator/prometheus
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: 725Mi
    requests:
      cpu: 50m
      memory: 650Mi
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: ENV
      value: q2
    - name: DBURL
      value: jdbc:oracle:thin:@dmv06-scan.adeo.no:1521/sporingslogg_q2_ha
    - name: SPORINGSLOGG_AIVEN_KAFKA_TOPIC
      value: pensjonsamhandling.public-sporingslogg-loggmeldingmottatt-q2
    - name: SPORINGSLOGG_AIVEN_KAFKA_GROUP
      value: sporingslogg-loggmeldingmottatt-q2
    - name: DIFI_TOKEN_CONFIGURATION_URL
      value: https://oidc-ver2.difi.no/idporten-oidc-provider/.well-known/openid-configuration
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/.well-known/openid-configuration
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name=q2"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm
    logging:
      destinations:
        - id: loki
