# Miljøspesifikke verdier: metadata.namespace, spec.ingresses, og spec.env-verdiene
# image-navnet injiseres med riktig versjon
#
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8088
  ingresses:
    - "https://sporingslogg-q2.nais.preprod.local"
    - "https://sporingslogg-q2.dev.intern.nav.no"
  secureLogs:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /sporingslogg/prometheus
  liveness:
    path: /sporingslogg/api/ping
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    path: /sporingslogg/api/ping
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/sporingslogg_q2-user
        mountPath: /secrets/oracle_creds
      - kvPath: /serviceuser/data/dev/srvsporingslogg
        mountPath: /secrets/serviceuser
  webproxy: true
  env:
    - name: LDAP_URL
      value: "ldaps://ldapgw.preprod.local"
    - name: LDAP_BASEDN
      value: "DC=preprod,DC=local"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=preprod,dc=local"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=preprod,dc=local"
    - name: SPORINGSLOGGDB_URL
      value: "jdbc:oracle:thin:@a01dbfl042.adeo.no:1521/SPORINGSLOGG_Q2"
    - name: SPORINGSLOGGDB_USERNAME
      value: "SPORINGSLOGG"
    - name: NO_NAV_SPORINGSLOGG_KAFKA_SERVERS
      value: "b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443"
    - name: NO_NAV_SPORINGSLOGG_OIDC_ISSUERLIST
      value: "https://oidc-ver2.difi.no/idporten-oidc-provider/,https://isso-q.adeo.no:443/isso/oauth2"
    - name: NO_NAV_SPORINGSLOGG_OIDC_JWKSLIST
      value: "https://oidc-ver2.difi.no/idporten-oidc-provider/jwk,https://isso-q.adeo.no:443/isso/oauth2/connect/jwk_uri"
# Skal være satt til 4 (Bank-ID) når man går mot ID-porten, 0 ellers
    - name: SPORINGSLOGG_CHECK_AUTHLEVEL
      value: "4"

