# Miljøspesifikke verdier: metadata.namespace, spec.ingresses, og spec.env-verdiene
# image-navnet injiseres med riktig versjon
#
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg-t4
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8088
  ingresses:
    - "https://sporingslogg-t4.nais.preprod.local"
  secureLogs:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  liveness:
    path: /sporingslogg/api/ping
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    path: /sporingslogg/api/ping
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  prometheus:
    enabled: true
    path: /sporingslogg/prometheus
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  vault: 
    enabled: true
    # erstatter kun pw for now, tar evt med user, url og evt srvuser senere. Fordel: endringer gjort av drift havner i vault
    paths:
      - kvPath: oracle/data/dev/creds/sporingslogg_t4-user
        mountPath: /secrets/database/credentials
  env:
    - name: LDAP_URL
      value: "ldaps://ldapgw.test.local"
    - name: LDAP_BASEDN
      value: "DC=test,DC=local"
    - name: DB_PASSWORD_FILE
      value: "/secrets/database/credentials/password"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=test,dc=local"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=test,dc=local"
    - name: SPORINGSLOGGDB_URL
      value: "jdbc:oracle:thin:@d26dbfl029.test.local:1521/sporingslogg_t4"
    - name: SPORINGSLOGGDB_USERNAME
      value: "SPORINGSLOGG"
    - name: NO_NAV_SPORINGSLOGG_KAFKA_SERVERS
      value: "d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443"
# OIDC-ressursene er annerledes for idporten/openam
#Issuer:
#  https://stub-oidc-provider.azurewebsites.net
#Jwks: 
#  https://stub-oidc-provider.azurewebsites.net/certs
# Azure:
#   https://login.microsoftonline.com/d38f25aa-eab8-4c50-9f28-ebf92c1256f2/v2.0/
#   https://login.microsoftonline.com/navtestb2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten_ver1
# NAV STS i T
#   https://security-token-service-t4.nais.preprod.local
#   https://security-token-service-t4.nais.preprod.local/rest/v1/sts/jwks
#
# Issuerlist og jwkslist skal være kommaseparert med like mange, korresponderende elementer.
# Testet med fitnessetester, funker hvis issuer er først og sist i lista, nekter hvis den ikke er i lista
    - name: NO_NAV_SPORINGSLOGG_OIDC_ISSUERLIST
      value: "https://dummy.nav.no/issuer,https://security-token-service-t4.nais.preprod.local"
    - name: NO_NAV_SPORINGSLOGG_OIDC_JWKSLIST
      value: "https://dummy.nav.no/jwks,https://security-token-service-t4.nais.preprod.local/rest/v1/sts/jwks"
# Skal være satt til 4 (Bank-ID) når man går mot ID-porten, 0 ellers
    - name: SPORINGSLOGG_CHECK_AUTHLEVEL
      value: "0"
# Må sette opp web proxy hvis JWKS-URL er ekstern
#    - name: NO_NAV_SPORINGSLOGG_OIDC_PROVIDER_PROXYHOST
#      value: "webproxy-nais.nav.no"
#    - name: NO_NAV_SPORINGSLOGG_OIDC_PROVIDER_PROXYPORT
#      value: "8088"
      
