apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg-q2
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dsop-api
          namespace: personbruker
          cluster: dev-gcp
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sporingslogg-q2.nais.preprod.local"
    - "https://sporingslogg-q2.dev.intern.nav.no"
    - "https://sporingslogg-q2.dev-fss-pub.nais.io"
  secureLogs:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: actuator/prometheus
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  resources:
    limits:
      cpu: "1"
      memory: 2096Mi
    requests:
      cpu: 800m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/sporingslogg_q2-user
        mountPath: /secrets/oracle_creds
      - kvPath: /serviceuser/data/dev/srvsporingslogg
        mountPath: /secrets/serviceuser
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: ENV
      value: q2
    - name: DBURL
      value: jdbc:oracle:thin:@a01dbfl042.adeo.no:1521/SPORINGSLOGG_Q2
    - name: SPORINGSLOGG_KAFKA_TOPIC
      value: aapen-sporingslogg-loggmeldingMottatt
    - name: SPORINGSLOGG_KAFKA_GROUP
      value: KC-aapen-sporingslogg-loggmeldingMottatt
    - name: SPORINGSLOGG_AIVEN_KAFKA_TOPIC
      value: public-sporingslogg-loggmeldingmottatt-q2
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: DIFI_TOKEN_CONFIGURATION_URL
      value: https://oidc-ver2.difi.no/idporten-oidc-provider/.well-known/openid-configuration
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/.well-known/openid-configuration
