# Miljøspesifikke verdier: metadata.namespace, spec.ingresses, og spec.env-verdiene
# image-navnet injiseres med riktig versjon
#
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8088
  ingresses:
    - "https://sporingslogg.nais.adeo.no"
    - "https://sporingslogg.intern.nav.no"
  secureLogs:
    enabled: false
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  liveness:
    path: /sporingslogg/api/ping
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    path: /sporingslogg/api/ping
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  vault: 
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/sporingslogg_p-user
        mountPath: /secrets/oracle_creds
      - kvPath: /serviceuser/data/prod/srvsporingslogg
        mountPath: /secrets/serviceuser
  webproxy: true
  env:
    - name: LDAP_URL
      value: "ldaps://ldapgw.adeo.no"
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"
    - name: SPORINGSLOGGDB_URL
      value: "jdbc:oracle:thin:@a01dbfl043.adeo.no:1521/SPORINGSLOGG_P_HA"
    - name: SPORINGSLOGGDB_USERNAME
      value: "SPORINGSLOGG"
    - name: NO_NAV_SPORINGSLOGG_KAFKA_SERVERS
      value: "a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"
    - name: NO_NAV_SPORINGSLOGG_OIDC_ISSUERLIST
      value: "https://oidc.difi.no/idporten-oidc-provider/"
    - name: NO_NAV_SPORINGSLOGG_OIDC_JWKSLIST
      value: "https://oidc.difi.no/idporten-oidc-provider/jwk"
# Skal være satt til 4 (Bank-ID) når man går mot ID-porten, 0 ellers
    - name: SPORINGSLOGG_CHECK_AUTHLEVEL
      value: "4"
