apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dsop-api
          namespace: personbruker
          cluster: prod-gcp
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sporingslogg.intern.nav.no"
    - "https://sporingslogg.prod-fss-pub.nais.io"
  secureLogs:
    enabled: false
  prometheus:
    enabled: true
    path: actuator/prometheus
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/sporingslogg_p-user
        mountPath: /secrets/oracle_creds
      - kvPath: /serviceuser/data/prod/srvsporingslogg
        mountPath: /secrets/serviceuser
  webproxy: true
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: ENV
      value: p
    - name: DBURL
      value: jdbc:oracle:thin:@a01dbfl043.adeo.no:1521/SPORINGSLOGG_P_HA
    - name: SPORINGSLOGG_AIVEN_KAFKA_TOPIC
      value: pensjonsamhandling.public-sporingslogg-loggmeldingmottatt
    - name: SPORINGSLOGG_AIVEN_KAFKA_GROUP
      value: sporingslogg-loggmeldingmottatt
    - name: DIFI_TOKEN_CONFIGURATION_URL
      value: https://oidc.difi.no/idporten-oidc-provider/.well-known/openid-configuration
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.adeo.no/.well-known/openid-configuration
