CREATE SEQUENCE SPORINGS_LOGG_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SPORINGS_LOGG (
  ID          NUMBER(19, 0) NOT NULL,
  PERSON      VARCHAR(20) NOT NULL,
  MOTTAKER    VARCHAR(20) NOT NULL,
  TEMA        VARCHAR(20) NOT NULL,
  HJEMMEL     VARCHAR(100) NOT NULL,
  TIDSPUNKT   TIMESTAMP    NOT NULL,
  LEVERTE_DATA VARCHAR(4000) NOT NULL,
  SAMTYKKE_TOKEN VARCHAR(1000),
  CONSTRAINT SPORINGS_LOGG_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SPORINGS_LOGG_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX SPORINGS_LOGG_PERSON ON SPORINGS_LOGG(PERSON);

------------------------------
-- Disse skal kjøres ved opprydding/sletting

DROP TABLE SPORINGS_LOGG;
DROP SEQUENCE SPORINGS_LOGG_ID_SEQ;
