CREATE SEQUENCE SPORINGS_LOGG_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SPORINGS_LOGG (
  ID          NUMBER(19, 0) NOT NULL,
  PERSON      VARCHAR(20) NOT NULL,
  MOTTAKER    VARCHAR(20) NOT NULL,
  TEMA        VARCHAR(20) NOT NULL,
  HJEMMEL     VARCHAR(100) NOT NULL,
  TIDSPUNKT   TIMESTAMP    NOT NULL,
  LEVERTE_DATA CLOB NOT NULL,
  SAMTYKKE_TOKEN VARCHAR(1000),
  FORESPORSEL CLOB,
  LEVERANDOR  VARCHAR(20),
  CONSTRAINT SPORINGS_LOGG_PK PRIMARY KEY (ID)
);

CREATE INDEX SPORINGS_LOGG_PERSON ON SPORINGS_LOGG(PERSON);

-- Lagt til etter første versjon
ALTER TABLE SPORINGS_LOGG
  ADD FORESPORSEL CLOB;
ALTER TABLE SPORINGS_LOGG
  ADD LEVERANDOR VARCHAR(20);

------------------------------
-- Disse skal kjøres ved opprydding/sletting

DROP TABLE SPORINGS_LOGG;
DROP SEQUENCE SPORINGS_LOGG_ID_SEQ;


-- konv til clob (ingen må bruke basen imens, og ny kode med @Lob må deployes rett etter)
alter table SPORINGS_LOGG add LEVERTE_DATA2 varchar2(4000);
update SPORINGS_LOGG set LEVERTE_DATA2 = LEVERTE_DATA;
commit;
alter table SPORINGS_LOGG modify (LEVERTE_DATA null);
update SPORINGS_LOGG set LEVERTE_DATA = null;
commit;
alter table SPORINGS_LOGG modify LEVERTE_DATA long;
alter table SPORINGS_LOGG modify LEVERTE_DATA clob;
update SPORINGS_LOGG set LEVERTE_DATA = LEVERTE_DATA2;
commit;
alter table SPORINGS_LOGG modify (LEVERTE_DATA not null);
alter table SPORINGS_LOGG drop column LEVERTE_DATA2;
ALTER INDEX SPORINGS_LOGG_PK REBUILD ONLINE;
ALTER INDEX SPORINGS_LOGG_PERSON REBUILD ONLINE;