name: Bygg og deploy sandbox v2

on:
  push:
    branches:
      - sandbox

jobs:
  build_and_tag:
    name: 'Build and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      checks: write
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      # PULL REPO
      - name: Pull repo
        uses: actions/checkout@v5

      # JAVA
      - name: Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'

      # Gradlew Build and run test
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 8.9
      - name: Build and test with Gradle
        run: ./gradlew build --stacktrace

      - name: Nais docker-build
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonsamhandling
          tag: ${{ github.event.repository.name }}
          pull: true
          image_suffix: "sandbox"

  deployToQ2:
    permissions:
      contents: "read"
      id-token: "write"
    name: 'Deploy NAIS Q2'
    needs: build_and_tag
    outputs:
      image: ${{ needs.build_and_tag.outputs.image }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to Q2
        uses: nais/deploy/actions/deploy@v2
        env:
          "CLUSTER": dev-fss
          "RESOURCE": nais/dev_q2.yaml
          "IMAGE": ${{ needs.build_and_tag.outputs.image }}

  deployTopicToQ2:
    permissions:
      contents: "read"
      id-token: "write"
    name: 'Deploy topics DEV'
    needs: deployToQ2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Deploy public-sporingslogg-loggmeldingMottatt-q2 to pensjonsamhandling namespace
        uses: nais/deploy/actions/deploy@v2
        env:
          "CLUSTER": dev-gcp
          "RESOURCE": nais/topics/loggmeldingmottatt-q2.yaml
