name: Bygg alle brancher

on:
  push:
    branches:
      - '*'
      - '*/**'
      - '!release/*'
      - '!master'

jobs:
  bygg:
    name: 'Bygg alle brancher'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v5

      - name: 'Java 21'
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: oracle
          cache: 'gradle'

      - name: Set timezone
        run:
          export TZ=CET

      # Gradlew Build and run test
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9
      - name: Build and test with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build --stacktrace