name: Bygg alle brancher

on:
  push:
    branches:
      - '*'
      - '*/**'
      - '!release/*'
      - '!master'

jobs:
  bygg:
    name: 'Bygg alle brancher'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Java 21'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
          cache: 'gradle'

      - name: 'Bugg og test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=CET
          ./gradlew build --stacktrace
