name: "Deploy to production"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to deploy (e.g. 2020.01.01-12.55-a1b2c3d4e5f6)"
        required: true

jobs:
  deployToProd:
    name: "Deploy to Prod"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/prod.yaml
          IMAGE: "ghcr.io/navikt/sporingslogg/sporingslogg-nais:${{ github.event.inputs.version }}"
          TEAM: pensjonsamhandling
